### ISSUE TITLE
ValueError: index can't contain negative values

### ISSUE THREAD

**Issue by setnes** [hotdogee/solar-eclipse-timelapse-aligner#3]
This looks like a pretty neat program, but I can't seem to get it to work.

```
Traceback (most recent call last):
  File "/home/setnes/git/solar-eclipse-timelapse-aligner/eclipse-aligner.py", line 564, in <module>
    output_image(jpg_path, circles_data[jpg_path.name])
  File "/home/setnes/git/solar-eclipse-timelapse-aligner/eclipse-aligner.py", line 141, in output_image
    padded = np.pad(img, ((pad_y, pad_y), (pad_x, pad_x), (0, 0)))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/numpy/lib/arraypad.py", line 748, in pad
    pad_width = _as_pairs(pad_width, array.ndim, as_index=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/numpy/lib/arraypad.py", line 518, in _as_pairs
    raise ValueError("index can't contain negative values")
ValueError: index can't contain negative values
```

I also tried running the windows version in Wine and got the same negative values error.

**Comment by dmcrlsn** [comment]
See this post for how I was able to work around this problem:

cloudynights.com/topic/895254-imppg-align-annular-eclipse/?p=13012539

**Comment by setnes** [comment]
@dmcrlsn This worked for me as well.  Thanks a bunch!  I still needed to manually adjust the circles JSON file to align some of my images.  I also found a way to use PIPP instead of this tool, but this tool did a better job in one shot where PIPP needs to be used in two passes for the eclipse.

**Comment by setnes** [comment]
For what it's worth, I found if you enable the moon angle logic using --fix_angle that the original version works, and the patched version doesn't work with the moon.  I think most people would want to use this without moon angle detection though.

**Comment by chvvkumar** [comment]
If anyone else wants to implement this and make an executable, here is how I did it to incorporate @dmcrlsn's fixes using VSCode, Python3.7 under Windows 11:

- Clone this repo
- Make the changes as suggested i.e. change `canvas_size = (sun_mask_r + moon_mask_r * 2) * 2` to `canvas_size = max( img_h, img_w )`
- Create a venv and activate it
- Install all the required deps `pip install psutil opencv-python numpy scipy click tqdm pyinstaller`
- Build the EXE file and include all the libs within it `pyinstaller --onefile eclipse-aligner.py --hidden-import=psutil --hidden-import=cv2 --hidden-import=numpy --hidden-import=scipy --hidden-import=click --hidden-import=tqdm`
- This will create an EXE under the new `dist` folder
- Copy the EXE and replace the EXE from the archive in the release page in this repo
